name: Code Quality

on:
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Auto-format suggestion
        if: failure()
        run: |
          echo "❌ Code formatting issues found!"
          echo "Run 'npm run format' locally to fix formatting issues."
          echo "Then commit and push the changes."
